--- #YAML:1.0
name:                HTML-EditableTable
version:             0.20
abstract:            Classes for html presentation of tabular data with view and edit modes.
license:             perl
author:              
    - Andy Espenscheid <aespen@swbell.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
